name: Build And Deploy

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Node.js
      uses: actions/setup-node@master
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Push js and css task
      env:
        CDN_TOKEN: ${{ secrets.CDN_TOKEN }}
      run:
           cd ~ && 
           sudo mkdir cdn/ && 
           sudo git clone https://github.com/GodzzZZZ/BlogCDN.git && 
           git config --global user.name "GodzzZZZ" && 
           git config --global user.email "godzzzzz@qq.com" &&
           cd ~/BlogCDN/ &&
           sudo touch date &&
           time1=$(date) &&
           sudo echo $time1 > date &&
           find ./ -iname '1.css' -exec sudo git rm {} \; &&
           find ./ -iname 'main.css' -exec sudo git rm {} \; &&
           find ./ -iname '1.js' -exec sudo git rm {} \; &&
           find ./ -iname 'main.js' -exec sudo git rm {} \; &&
           echo '------------------ rm success -----------------------' &&
           find ~/work/BlogV2/BlogV2/build/static/css/ -iname '1.*.css' -exec sudo cp {} ~/cdn/1.css \; &&
           find ~/work/BlogV2/BlogV2/build/static/css/ -iname 'main.*.css' -exec sudo cp {} ~/cdn/main.css \; &&
           find ~/work/BlogV2/BlogV2/build/static/js/ -iname '1.*.js' -exec sudo cp {} ~/cdn/1.js \; &&
           find ~/work/BlogV2/BlogV2/build/static/js/ -iname 'main.*.js' -exec sudo cp {} ~/cdn/main.js \; &&
           sudo mv ~/cdn/* ~/BlogCDN/ &&
           echo '------------------ move success ---------------------' &&
           sudo git add . &&
           sudo git commit -m 'Update CDN file' &&
           sudo git push https://GodzzZZZ:$CDN_TOKEN@github.com/GodzzZZZ/BlogCDN.git &&
           echo '------------------ push success ---------------------' &&
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
