name: Build And Deploy to Server

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@master
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          git config --global user.email "github-actions[bot].pipelining@qq.com"
          git config --global user.name "github-actions[bot]"
          cd /root
          git clone git@github.com:1ess/deploy.git
          cd deploy/
          rm static/css/*.css
          rm static/js/*.js
          cp ~/nginx/html/blog/static/css/*.css static/css/
          cp ~/nginx/html/blog/static/js/*.js static/js/
          git add .
          git commit -m 'Add New Version Of Blog!'
          git push
          sed -i "s/\href=\"\//\href=\"https:\/\/cdn.jsdelivr.net\/gh\/1ess\/deploy\//g" ~/nginx/html/blog/index.html
          rm -rf /root/deploy/