name: Build And Deploy

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@master
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Push js and css task
      env:
        GITHUB_PWD: ${{ secrets.GITHUB_PWD }}
      run:
           pwd &&
           cd ../.. && 
           sudo mkdir cdn/ && 
           sudo git clone https://github.com/GodzzZZZ/BlogCDN.git && 
           find ./BlogV2/BlogV2/build/static/css/ -iname '1.*.css' -exec cp {} ./cdn/1.css \; &&
           find ./BlogV2/BlogV2/build/static/css/ -iname 'main.*.css' -exec cp {} ./cdn/main.css \; &&
           find ./BlogV2/BlogV2/build/static/js/ -iname '1.*.js' -exec cp {} ./cdn/1.js \; &&
           find ./BlogV2/BlogV2/build/static/js/ -iname 'main.*.js' -exec cp {} ./cdn/main.js \; &&
           sudo rm -rf ./BlogCDN/* &&
           sudo mv ./cdn/* ./BlogCDN/ &&
           git config --global user.name "GodzzZZZ" && 
           git config --global user.email "godzzzzz@qq.com" &&
           cd ./BlogCDN/ &&
           sudo git status &&1
           ls -la &&
           sudo git add . &&
           sudo git commit -m 'Update CDN file' &&
           sudo git remote set-url --push origin https://GodzzZZZ:$GITHUB_PWD@github.com/GodzzZZZ/BlogCDN
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
