name: Build And Deploy

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Node.js
      uses: actions/setup-node@master
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Push js and css task
      env:
        GITHUB_PWD: ${{ secrets.GITHUB_PWD }}
        ID_RSA: ${{secrets.ID_RSA}}
        ID_RSA_PUB: ${{secrets.ID_RSA_PUB}}
      run:
           sudo mkdir ~/.ssh &&
           sudo touch ~/.ssh/id_rsa &&
           sudo touch ~/.ssh/id_rsa.pub &&
           sudo chmod 777 ~/.ssh/id_rsa && 
           sudo chmod 777 ~/.ssh/id_rsa.pub && 
           sudo touch ~/.ssh/known_hosts &&
           sudo chmod 777 ~/.ssh/known_hosts && 
           sudo ssh-keyscan -H github.com >> ~/.ssh/known_hosts &&
           sudo echo 'create success' &&
           sudo echo $ID_RSA &&
           sudo echo $ID_RSA_PUB &&
           sudo echo $ID_RSA > ~/.ssh/id_rsa &&
           sudo echo $ID_RSA_PUB > ~/.ssh/id_rsa.pub &&
           cd ../.. && 
           sudo mkdir cdn/ && 
           sudo git clone git@github.com:GodzzZZZ/BlogCDN.git && 
           find ./BlogV2/BlogV2/build/static/css/ -iname '1.*.css' -exec sudo cp {} ./cdn/1.css \; &&
           find ./BlogV2/BlogV2/build/static/css/ -iname 'main.*.css' -exec sudo cp {} ./cdn/main.css \; &&
           find ./BlogV2/BlogV2/build/static/js/ -iname '1.*.js' -exec sudo cp {} ./cdn/1.js \; &&
           find ./BlogV2/BlogV2/build/static/js/ -iname 'main.*.js' -exec sudo cp {} ./cdn/main.js \; &&
           sudo rm -rf ./BlogCDN/* &&
           sudo mv ./cdn/* ./BlogCDN/ &&
           git config --global user.name "GodzzZZZ" && 
           git config --global user.email "godzzzzz@qq.com" &&
           cd ./BlogCDN/ &&
           sudo git add . &&
           sudo git commit -m 'Update CDN file' &&
           sudo git push -u origin master
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
