name: Build And Deploy

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@master
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Push js and css task
      run: cd / && 
           sudo git clone git@github.com:GodzzZZZ/BlogCDN.git && 
           sudo rm -rf /BlogCDN/*
           find /BlogCDN/ -iname '1.*.css' -exec cp {} ./1.css \; &&
           find /BlogCDN/ -iname 'main.*.css' -exec cp {} ./main.css \; &&
           find /BlogCDN/ -iname '1.*.js' -exec cp {} ./1.js \; &&
           find /BlogCDN/ -iname 'main.*.js' -exec cp {} ./main.js \; &&
           ls -l /BlogCDN/
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
